name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ['3.10']
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade ruff mypy

    - name: ruff
      run: |
        ruff --version
        ruff .
        ruff format --check .

    - name: mypy
      run: |
        mypy --version
        rm -rf .mypy_cache
        mypy ${{ github.event.repository.name }}
